services:
  backend:
    image: myapp-backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    working_dir: /app
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./logs/django:/app/logs   # ← Djangoログをホストと共有
    env_file:
      - /home/ec2-user/.env.deploy   # ← 絶対パスに変更
    ports:
      - "8000:8000"
    restart: always



  nginx:
    image: myapp-nginx  # ← build: を image: に変更
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./logs/nginx:/var/log/nginx   # ← Nginxログをホストと共有
    env_file:
      - /home/ec2-user/.env.deploy   # ← 絶対パスに変更
    restart: always
