# Generated by Django 4.2.20 on 2025-03-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafemap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
