# Generated by Django 4.2.20 on 2025-05-17 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cafemap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allow_sync', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafemap.map')),
            ],
        ),
        migrations.CreateModel(
            name='CafeSharedMapRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafemap.cafe')),
                ('shared_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafemap.sharedmap')),
            ],
        ),
        migrations.CreateModel(
            name='UserSharedMapRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafemap.sharedmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'shared_map')},
            },
        ),
    ]
