# Generated by Django 4.2.20 on 2025-11-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafemap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'share_channel',
            },
        ),
        migrations.AddField(
            model_name='sharedmap',
            name='direct_access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharedmap',
            name='direct_last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SharedMapAnalyzeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_label', models.CharField(blank=True, max_length=255, null=True)),
                ('share_link_url', models.TextField()),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafemap.sharechannel')),
                ('shared_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafemap.sharedmap')),
            ],
            options={
                'db_table': 'shared_map_analyze_link',
            },
        ),
        migrations.AddIndex(
            model_name='sharechannel',
            index=models.Index(fields=['is_active', 'sort_order'], name='share_chann_is_acti_58bc49_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedmapanalyzelink',
            index=models.Index(fields=['shared_map'], name='shared_map__shared__118368_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedmapanalyzelink',
            index=models.Index(fields=['shared_map', 'is_active'], name='shared_map__shared__090e4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedmapanalyzelink',
            unique_together={('shared_map', 'channel')},
        ),
    ]
