# Generated by Django 4.2.20 on 2025-03-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafemaprelation',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafemap.map'),
        ),
    ]
