# Generated by Django 4.2.20 on 2025-04-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafemap', '0002_alter_cafemaprelation_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
