# Generated by Django 4.2.20 on 2025-11-22 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafemap', '0003_populate_share_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('map_style', models.CharField(default='default', max_length=50)),
                ('icon_variant', models.CharField(default='photo', max_length=50)),
                ('icon_color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon_size', models.IntegerField(default=48)),
                ('show_labels', models.BooleanField(default=True)),
                ('border_color', models.CharField(blank=True, max_length=7, null=True)),
                ('background_color', models.CharField(blank=True, max_length=7, null=True)),
                ('is_snapshot', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customs', to=settings.AUTH_USER_MODEL)),
                ('original_custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='cafemap.custom')),
            ],
            options={
                'db_table': 'custom',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_setting',
            },
        ),
        migrations.AlterField(
            model_name='sharedmap',
            name='original_map',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_map', to='cafemap.map'),
        ),
        migrations.AddField(
            model_name='map',
            name='custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='cafemap.custom'),
        ),
        migrations.AddField(
            model_name='sharedmap',
            name='custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_maps', to='cafemap.custom'),
        ),
        migrations.CreateModel(
            name='UserCustomRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafemap.custom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_custom_relation',
                'unique_together': {('user', 'custom')},
            },
        ),
        migrations.AddIndex(
            model_name='custom',
            index=models.Index(fields=['created_by_user'], name='custom_created_81faa1_idx'),
        ),
        migrations.AddIndex(
            model_name='custom',
            index=models.Index(fields=['is_public', 'is_snapshot'], name='custom_is_publ_c711bd_idx'),
        ),
    ]
