# Generated by Django 4.2.20 on 2025-04-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafemap', '0003_cafe_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='price_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
