# Generated by Django 4.2.20 on 2025-05-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafemap', '0004_cafe_price_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
