# Generated by Django 4.2.20 on 2025-11-30 05:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafemap', '0006_chatsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='custom_places/')),
                ('place_type', models.CharField(blank=True, choices=[('photo_spot', '写真スポット'), ('meeting_point', '待ち合わせ場所'), ('viewpoint', '景色の良い場所'), ('memorial', '記念碑・モニュメント'), ('other', 'その他')], max_length=50, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_place',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomPlaceMapRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_relations', to='cafemap.customplace')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_place_relations', to='cafemap.map')),
            ],
            options={
                'db_table': 'custom_place_map_relation',
                'indexes': [models.Index(fields=['map', 'is_visible'], name='custom_plac_map_id_a93fd7_idx')],
                'unique_together': {('map', 'custom_place')},
            },
        ),
        migrations.AddIndex(
            model_name='customplace',
            index=models.Index(fields=['owner', '-created_at'], name='custom_plac_owner_i_632c60_idx'),
        ),
        migrations.AddIndex(
            model_name='customplace',
            index=models.Index(fields=['latitude', 'longitude'], name='custom_plac_latitud_b87f00_idx'),
        ),
    ]
